### ISSUE TITLE
Exoplayer Version Problem

### ISSUE THREAD

**Issue by yavuzirfanoglu** [relateddigital/visilabs-android#32]
Hello there.

We have integrated your sdk to our project. However your sdk uses newer version of the exoplayer. That causes a problem for us. We cannot update our exoplayer version currently. We reverted our visilabs version to 5.5.0 in order to match our exoplayer versions. Is using visilabs 5.5.0 a problem?  What is  the minimum required visilabs version?

Sincerely.

**Comment by umutalparslan** [comment]
> Hello there.
> 
> We have integrated your sdk to our project. However your sdk uses newer version of the exoplayer. That causes a problem for us. We cannot update our exoplayer version currently. We reverted our visilabs version to 5.5.0 in order to match our exoplayer versions. Is using visilabs 5.5.0 a problem? What is the minimum required visilabs version?
> 
> Sincerely.

Hello @yavuzirfanoglu,

We recommend that you always use the latest version Visilabs SDK.
If you wish, you can force and use your own version of Exoplayer.

You should paste it at the bottom of app level build.gradle.
```
configurations.all {
        resolutionStrategy {
            force("com.google.android.exoplayer:exoplayer:your_version_here"
            )
        }
}
```

Best regards

**Comment by yavuzirfanoglu** [comment]
Thanks it works now!
