### ISSUE TITLE
build gradle'a eklememe rağmen class'lar bulunamıyor

### ISSUE THREAD

**Issue by maqtay** [relateddigital/visilabs-android#37]
Selamlar, projeyi build gradle'a eklememe rağmen class'ları bulamıyor proje. Hiç bir şekilde import edemiyorum.

build.gradle - app

` implementation 'com.github.relateddigital:visilabs-android:6.1.6'`

build.gradle - project
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by umutalparslan** [comment]
Merhaba,

Biz tekrar kontrol ettiğimizde sorunsuz bir şekilde ekleyebildik. Proje tarafında sdkmız görüldü. Ekran görüntüsü ve alıyorsanız hata loglarını iletebilir misiniz?

Teşekkürler
